###  (Optional But Recommended) Download This Extension: https://marketplace.visualstudio.com/items?itemName=humao.rest-client 

GET http://localhost:8000/get/string

###

GET http://localhost:8000/get/json

### 

POST http://localhost:8000/post/headers
content-type: application/json

{

    "example": "Hello, World"
    
}